CREATE TABLE IF NOT EXISTS Migration (id INTEGER PRIMARY KEY);

CREATE TABLE IF NOT EXISTS App (
	id TEXT PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	description TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS Domain (
	name TEXT PRIMARY KEY NOT NULL,
	app TEXT NOT NULL,
	FOREIGN KEY (app) REFERENCES App(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS User (
	id TEXT PRIMARY KEY NOT NULL,
	name TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	email TEXT DEFAULT '' UNIQUE,
	role INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS AppManager (
	app TEXT NOT NULL,
	user TEXT NOT NULL,
	PRIMARY KEY (app, user),
	FOREIGN KEY (app) REFERENCES App(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (user) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO Migration VALUES (1);
