-- Initial scheme
CREATE TABLE IF NOT EXISTS Migration (id INTEGER PRIMARY KEY);

CREATE TABLE IF NOT EXISTS App (
	id TEXT PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	description TEXT DEFAULT '',
	created_at TEXT NOT NULL DEFAULT now
);

CREATE TABLE IF NOT EXISTS Domain (
	name TEXT NOT NULL,
	app TEXT NOT NULL REFERENCES App(id) ON UPDATE CASCADE ON DELETE CASCADE,
	created_at TEXT NOT NULL DEFAULT now,
	PRIMARY KEY (name, app)
);

CREATE TABLE IF NOT EXISTS User (
	id TEXT PRIMARY KEY,
	name TEXT UNIQUE NOT NULL COLLATE NOCASE,
	email TEXT DEFAULT '' COLLATE NOCASE,
	role INTEGER NOT NULL DEFAULT 1 REFERENCES Role(id) ON UPDATE CASCADE,
	created_at TEXT NOT NULL DEFAULT now
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_name ON User (name COLLATE NOCASE);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON User (email COLLATE NOCASE) WHERE email != '';

CREATE TABLE IF NOT EXISTS Role (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AppUser (
	app TEXT REFERENCES App(id) ON UPDATE CASCADE ON DELETE CASCADE,
	user TEXT REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
	role INTEGER NOT NULL DEFAULT 1 REFERENCES Role(id) ON UPDATE CASCADE,
	created_at TEXT NOT NULL DEFAULT now,
	PRIMARY KEY (app, user)
);

CREATE TABLE IF NOT EXISTS Session (
	id TEXT PRIMARY KEY NOT NULL,
	user TEXT NOT NULL REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
	device TEXT DEFAULT 'Unknown device',
	token TEXT NOT NULL UNIQUE,
	expires_at TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT now,
	last_used TEXT NOT NULL DEFAULT now
);

CREATE TABLE IF NOT EXISTS OAuthToken (
	id INTEGER PRIMARY KEY,
	user TEXT NOT NULL REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
	token TEXT NOT NULL,
	provider TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT now,
	expires_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Password (
	id TEXT PRIMARY KEY,
	user TEXT NOT NULL REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
	algorithm TEXT NOT NULL DEFAULT 'argon2', -- Used for upgrading user's password to a newer algorithm
	password TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT now
);

CREATE TABLE IF NOT EXISTS PasskeyCredential (
	id TEXT PRIMARY KEY,
	user TEXT NOT NULL REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
	credential_id TEXT NOT NULL UNIQUE,
	credential_type TEXT NOT NULL,
	last_used TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT now
);

-- Insert default roles
INSERT INTO Role (id, name) VALUES (1, 'User'), (2, 'Manager');
