// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type App struct {
	Id          string  `db:"id" json:"id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
}

type Appuser struct {
	App  *string `db:"app" json:"app"`
	User *string `db:"user" json:"user"`
	Role int64   `db:"role" json:"role"`
}

type Domain struct {
	Name string `db:"name" json:"name"`
	App  string `db:"app" json:"app"`
}

type Migration struct {
	Id int64 `db:"id" json:"id"`
}

type Oauthtoken struct {
	Id        int64     `db:"id" json:"id"`
	User      string    `db:"user" json:"user"`
	Token     string    `db:"token" json:"token"`
	Provider  string    `db:"provider" json:"provider"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	ExpiresAt time.Time `db:"expires_at" json:"expiresAt"`
}

type Role struct {
	Id   int64  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type Session struct {
	Id        string  `db:"id" json:"id"`
	User      string  `db:"user" json:"user"`
	Device    *string `db:"device" json:"device"`
	LastUsed  int64   `db:"last_used" json:"lastUsed"`
	ExpiresAt int64   `db:"expires_at" json:"expiresAt"`
	Token     string  `db:"token" json:"token"`
}

type User struct {
	Id       string  `db:"id" json:"id"`
	Name     string  `db:"name" json:"name"`
	Email    *string `db:"email" json:"email"`
	Password *string `db:"password" json:"password"`
	Role     int64   `db:"role" json:"role"`
}
