// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type App struct {
	Id          string      `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	CreatedAt   interface{} `db:"created_at" json:"createdAt"`
}

type Appuser struct {
	App       *string     `db:"app" json:"app"`
	User      *string     `db:"user" json:"user"`
	Role      int64       `db:"role" json:"role"`
	CreatedAt interface{} `db:"created_at" json:"createdAt"`
}

type Domain struct {
	Name      string      `db:"name" json:"name"`
	App       string      `db:"app" json:"app"`
	CreatedAt interface{} `db:"created_at" json:"createdAt"`
}

type Migration struct {
	Id int64 `db:"id" json:"id"`
}

type Oauthtoken struct {
	Id        int64       `db:"id" json:"id"`
	User      string      `db:"user" json:"user"`
	Token     string      `db:"token" json:"token"`
	Provider  string      `db:"provider" json:"provider"`
	CreatedAt interface{} `db:"created_at" json:"createdAt"`
	ExpiresAt string      `db:"expires_at" json:"expiresAt"`
}

type Passkeycredential struct {
	Id             string      `db:"id" json:"id"`
	User           string      `db:"user" json:"user"`
	CredentialId   string      `db:"credential_id" json:"credentialId"`
	CredentialType string      `db:"credential_type" json:"credentialType"`
	LastUsed       string      `db:"last_used" json:"lastUsed"`
	CreatedAt      interface{} `db:"created_at" json:"createdAt"`
}

type Password struct {
	User      string      `db:"user" json:"user"`
	Algorithm string      `db:"algorithm" json:"algorithm"`
	Password  string      `db:"password" json:"password"`
	CreatedAt interface{} `db:"created_at" json:"createdAt"`
}

type Role struct {
	Id   int64  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type Session struct {
	Id        string      `db:"id" json:"id"`
	User      string      `db:"user" json:"user"`
	Device    *string     `db:"device" json:"device"`
	Token     string      `db:"token" json:"token"`
	ExpiresAt string      `db:"expires_at" json:"expiresAt"`
	CreatedAt interface{} `db:"created_at" json:"createdAt"`
	LastUsed  interface{} `db:"last_used" json:"lastUsed"`
}

type User struct {
	Id        string      `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	Email     *string     `db:"email" json:"email"`
	Role      int64       `db:"role" json:"role"`
	CreatedAt interface{} `db:"created_at" json:"createdAt"`
}
